"""
RootOps V2 — GitHub Client

Integrates with the GitHub API to create branches, commit fixes,
and open Pull Requests as part of the Auto-Healing pipeline.
Uses PyGithub for authenticated operations.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from github import Github, GithubException, InputGitTreeElement

from app.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


def _get_github() -> Github:
    """Create an authenticated GitHub client."""
    token = settings.GITHUB_TOKEN
    if not token:
        raise RuntimeError(
            "GITHUB_TOKEN is not set. Configure it in .env or environment variables."
        )
    return Github(token)


async def create_fix_pr(
    repo_full_name: str,
    file_path: str,
    new_content: str,
    fix_title: str,
    fix_description: str,
    *,
    base_branch: str = "main",
) -> dict:
    """Create a branch, commit a fix, and open a Pull Request.

    Args:
        repo_full_name: GitHub repo in 'owner/repo' format.
        file_path: Path of the file to fix (relative to repo root).
        new_content: The corrected file content.
        fix_title: PR title.
        fix_description: PR body with diagnosis and explanation.
        base_branch: Branch to target (default: main).

    Returns:
        Dict with PR URL and metadata.
    """
    gh = _get_github()

    try:
        repo = gh.get_repo(repo_full_name)
    except GithubException as e:
        raise RuntimeError(f"Could not access repo '{repo_full_name}': {e}")

    # ── 1. Create a fix branch ───────────────────────────────────
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    branch_name = f"rootops/auto-heal-{timestamp}"

    try:
        base_ref = repo.get_branch(base_branch)
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_ref.commit.sha,
        )
        logger.info("Created branch: %s", branch_name)
    except GithubException as e:
        raise RuntimeError(f"Could not create branch: {e}")

    # ── 2. Commit the fix ────────────────────────────────────────
    try:
        # Get the current file to preserve metadata
        existing_file = repo.get_contents(file_path, ref=base_branch)
        repo.update_file(
            path=file_path,
            message=f"fix: {fix_title}\n\nAuto-generated by RootOps Semantic Engine",
            content=new_content,
            sha=existing_file.sha,
            branch=branch_name,
        )
        logger.info("Committed fix to %s on branch %s", file_path, branch_name)
    except GithubException as e:
        raise RuntimeError(f"Could not commit fix: {e}")

    # ── 3. Open the Pull Request ─────────────────────────────────
    try:
        pr_body = (
            f"## 🤖 RootOps Auto-Heal\n\n"
            f"**Diagnosis:** {fix_title}\n\n"
            f"{fix_description}\n\n"
            f"---\n"
            f"*This PR was automatically generated by RootOps Semantic Engine "
            f"after correlating production logs with source code.*"
        )

        pr = repo.create_pull(
            title=f"🤖 [RootOps] {fix_title}",
            body=pr_body,
            head=branch_name,
            base=base_branch,
        )

        logger.info("Created PR #%d: %s", pr.number, pr.html_url)

        return {
            "pr_number": pr.number,
            "pr_url": pr.html_url,
            "branch": branch_name,
            "file_path": file_path,
            "status": "created",
        }

    except GithubException as e:
        raise RuntimeError(f"Could not create PR: {e}")
